[tool.poetry]
name = "ai-server"
version = "0.1.0"
description = ""
authors = ["Tarasikee <taras@deepinsight.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
